// const data = {
//   //   users: [
//   //     {
//   //       name: 'Basir',
//   //       email: 'admin@example.com',
//   //       password: bcrypt.hashSync('123456'),
//   //       isAdmin: true,
//   //     },
//   //     {
//   //       name: 'John',
//   //       email: 'user@example.com',
//   //       password: bcrypt.hashSync('123456'),
//   //       isAdmin: false,
//   //     },
//   //   ],
//   products: [
//     {
//       _id: '2',
//       name: 'The Bucket List (DVD)',
//       description: null,
//       bestSellingRank: 13920,
//       countInStock: 0,
//       thumbnailImage:
//         'http://img.bbystatic.com/BestBuy_US/images/products/8801/8801326s.jpg',
//       price: 4.99,
//       url: 'http://www.bestbuy.com/site/the-bucket-list-dvd/8801326.p?_id=1848662&sku_id=8801326&cmp=RMX&ky=2d3GfEmNIzjA0vkzveHdZEBgpPCyMnLTJ',
//       category: 'Movie',
//       image:
//         'http://img.bbystatic.com/BestBuy_US/images/products/8801/8801326.jpg',
//       numReviews: 52,
//       shipping: null,
//       salePrice_range: '1 - 50',
//       object_id: '8801326',
//       categories: ['Movies & TV Shows'],
//     },
//     {
//       _id: '2',
//       name: 'Kicker - Battery Terminal Clamp',
//       description:
//         'Designed for use with a positive or negative battery terminal; splits the connection into 3 outputs; nickel-coated sol_id brass construction',
//       bestSellingRank: 13921,
//       thumbnailImage:
//         'http://img.bbystatic.com/BestBuy_US/images/products/9906/9906158_s.gif',
//       price: 31.99,
//       countInStock: 10,
//       rating: '4.5',
//       slug: 'Kicker',
//       url: 'http://www.bestbuy.com/site/kicker-battery-terminal-clamp/9906158.p?_id=1218193799228&sku_id=9906158&cmp=RMX&ky=2d3GfEmNIzjA0vkzveHdZEBgpPCyMnLTJ',
//       category: 'HardGood',
//       image:
//         'http://img.bbystatic.com/BestBuy_US/images/products/9906/9906158_sc.jpg',
//       numReviews: 2,
//       shipping: 'Free shipping',
//       salePrice_range: '1 - 50',
//       object_id: '9906158',
//       categories: ['Connectors'],
//     },
//     {
//       _id: '3',
//       name: 'TomTom - Multi-Sport GPS Watch with Heart Rate Monitor - Dark Gray',
//       description:
//         'Measures heart rate, speed, distance and elapsed time; water-resistant design; single-button control; graphical training partner; extra-large display',
//       bestSellingRank: 13923,
//       thumbnailImage:
//         'http://img.bbystatic.com/BestBuy_US/images/products/9919/9919992_54x108_s.gif',
//       price: 249.99,
//       countInStock: 10,
//       rating: '4.5',
//       slug: 'TomTom',
//       url: 'http://www.bestbuy.com/site/tomtom-multi-sport-gps-watch-with-heart-rate-monitor-dark-gray/9919992.p?_id=1219043690335&sku_id=9919992&cmp=RMX&ky=2d3GfEmNIzjA0vkzveHdZEBgpPCyMnLTJ',
//       category: 'HardGood',
//       image:
//         'http://img.bbystatic.com/BestBuy_US/images/products/9919/9919992_105x210_sc.jpg',
//       numReviews: 32,
//       shipping: 'Free shipping',
//       salePrice_range: '201 - 500',
//       object_id: '9919992',
//       categories: ['Sport, Running & GPS Watches'],
//     },
//     {
//       _id: '4',
//       name: 'Frig_idaire - 5,000 BTU Window Air Conditioner - White',
//       description:
//         '150 sq. ft. cooling capacity; 2 fan speeds; 2 cool settings; 2-way air direction control; antibacterial filter; quick-mount window mounting kit',
//       bestSellingRank: 13924,
//       thumbnailImage:
//         'http://img.bbystatic.com/BestBuy_US/images/products/9921/9921679_s.gif',
//       price: 139.99,
//       countInStock: 10,
//       rating: '4.5',
//       slug: 'Frig_idaire',
//       url: 'http://www.bestbuy.com/site/frig_idaire-5000-btu-window-air-conditioner-white/9921679.p?_id=1218195771966&sku_id=9921679',
//       category: 'HardGood',
//       image:
//         'http://img.bbystatic.com/BestBuy_US/images/products/9921/9921679_sc.jpg',
//       numReviews: 24,
//       shipping: 'Free shipping',
//       salePrice_range: '201 - 500',
//       object_id: '9921679',
//       categories: ['Window Air Conditioners'],
//     },
//     {
//       _id: '5',
//       name: 'Percy Jackson & the Olympians: The Lightning Thief (Blu-ray Disc)',
//       description: null,
//       bestSellingRank: 13925,
//       thumbnailImage:
//         'http://img.bbystatic.com/BestBuy_US/images/products/9931/9931039s.jpg',
//       price: 14.99,
//       url: 'http://www.bestbuy.com/site/percy-jackson-the-olympians-the-lightning-thief-blu-ray-disc/9931039.p?_id=2105871&sku_id=9931039&cmp=RMX&ky=2d3GfEmNIzjA0vkzveHdZEBgpPCyMnLTJ',
//       category: 'Movie',
//       image:
//         'http://img.bbystatic.com/BestBuy_US/images/products/9931/9931039.jpg',
//       numReviews: 85,
//       shipping: null,
//       salePrice_range: '1 - 50',
//       object_id: '9931039',
//       categories: ['Movies & TV Shows'],
//     },
//     {
//       _id: '6',
//       name: 'Epson - Ink Cartr_idge - Yellow Ink Cartr_idge, Workforce, Yellow - Yellow',
//       description: 'Yellow - Inkjet',
//       bestSellingRank: 13926,
//       thumbnailImage:
//         'http://img.bbystatic.com/BestBuy_US/images/products/9942/9942122_r.gif',
//       price: 13.19,
//       countInStock: 10,
//       rating: '4.5',
//       slug: 'Epson',
//       url: 'http://www.bestbuy.com/site/epson-ink-cartr_idge-yellow-ink-cartr_idge-workforce-yellow-yellow/9942122.p?_id=1218198442301&sku_id=9942122&cmp=RMX&ky=2d3GfEmNIzjA0vkzveHdZEBgpPCyMnLTJ',
//       category: 'HardGood',
//       image:
//         'http://img.bbystatic.com/BestBuy_US/images/products/9942/9942122_rc.jpg',
//       numReviews: 12,
//       shipping: 'Free shipping',
//       salePrice_range: '1 - 50',
//       object_id: '9942122',
//       categories: ['Printer Ink'],
//     },
//     {
//       _id: '7',
//       name: 'Skullcandy - Navigator On-Ear Headphones - Blue',
//       description:
//         'Supreme Sound technology; Rex Driver technology; sound isolation; leather-touch ear pillows; 3-button microphone; detachable cable; travel bag',
//       bestSellingRank: 13926,
//       thumbnailImage:
//         'http://img.bbystatic.com/BestBuy_US/images/products/8847/8847731_r.gif',
//       price: 79.99,
//       countInStock: 10,
//       rating: '4.5',
//       slug: 'Skullcandy',
//       url: 'http://www.bestbuy.com/site/skullcandy-navigator-on-ear-headphones-blue/8847731.p?_id=1218914354420&sku_id=8847731&cmp=RMX&ky=2d3GfEmNIzjA0vkzveHdZEBgpPCyMnLTJ',
//       category: 'HardGood',
//       image:
//         'http://img.bbystatic.com/BestBuy_US/images/products/8847/8847731_rc.jpg',
//       numReviews: 58,
//       shipping: 'Free shipping',
//       salePrice_range: '101 - 200',
//       object_id: '8847731',
//       categories: ['Headphones'],
//     },
//     {
//       _id: '8',
//       name: 'Skullcandy - Aviator Over-the-Ear Headphones - Black',
//       description:
//         'Supreme Sound technology; Rex Driver technology; sound isolation; 3-button microphone; detachable cable',
//       bestSellingRank: 13927,
//       thumbnailImage:
//         'http://img.bbystatic.com/BestBuy_US/images/products/8847/8847822_r.gif',
//       price: 119.99,
//       countInStock: 10,
//       rating: '4.5',
//       slug: 'Skullcandy',
//       url: 'http://www.bestbuy.com/site/skullcandy-aviator-over-the-ear-headphones-black/8847822.p?_id=1218914349022&sku_id=8847822&cmp=RMX&ky=2d3GfEmNIzjA0vkzveHdZEBgpPCyMnLTJ',
//       category: 'HardGood',
//       image:
//         'http://img.bbystatic.com/BestBuy_US/images/products/8847/8847822_rc.jpg',
//       numReviews: 19,
//       shipping: 'Free shipping',
//       salePrice_range: '201 - 500',
//       object_id: '8847822',
//       categories: ['Headphones'],
//     },
//     {
//       _id: '9',
//       name: '2-Year Acc_idental Protection Plan - Geek Squad',
//       description: '',
//       bestSellingRank: 13928,
//       thumbnailImage:
//         'http://img.bbystatic.com/BestBuy_US/images/products/nonsku/default_hardlines_s.gif',
//       price: 59.99,
//       url: 'http://www.bestbuy.com/site/2-year-acc_idental-protection-plan-geek-squad/9965872.p?_id=1218252611894&sku_id=9965872&cmp=RMX&ky=2d3GfEmNIzjA0vkzveHdZEBgpPCyMnLTJ',
//       category: 'BlackTie',
//       image:
//         'http://img.bbystatic.com/BestBuy_US/images/products/nonsku/default_hardlines_l.jpg',
//       numReviews: null,
//       shipping: 'Free shipping',
//       salePrice_range: '101 - 200',
//       object_id: '9965872',
//       categories: [null],
//     },
//     {
//       _id: '10',
//       name: 'Blue Crane Digital - Introduction to the Nikon D3200 Instructional DVD',
//       description:
//         "Compatible with Nikon D3200 cameras; instructional DVD; prov_ides an introduction to the camera's main controls and settings",
//       bestSellingRank: 13928,
//       thumbnailImage:
//         'http://img.bbystatic.com/BestBuy_US/images/products/8848/8848109_s.gif',
//       price: 21.99,
//       countInStock: 10,
//       rating: '4.5',
//       slug: 'Blue Crane Digital',
//       url: 'http://www.bestbuy.com/site/blue-crane-digital-introduction-to-the-nikon-d3200-instructional-dvd/8848109.p?_id=1218914356440&sku_id=8848109&cmp=RMX&ky=2d3GfEmNIzjA0vkzveHdZEBgpPCyMnLTJ',
//       category: 'HardGood',
//       image:
//         'http://img.bbystatic.com/BestBuy_US/images/products/8848/8848109_sc.jpg',
//       numReviews: 27,
//       shipping: null,
//       salePrice_range: '1 - 50',
//       object_id: '8848109',
//       categories: ['Camera Instructional DVDs'],
//     },
//     {
//       _id: '11',
//       name: '3-Year Acc_idental Protection Plan - Geek Squad',
//       description: '',
//       bestSellingRank: 13931,
//       thumbnailImage:
//         'http://img.bbystatic.com/BestBuy_US/images/products/nonsku/default_hardlines_s.gif',
//       price: 174.98,
//       url: 'http://www.bestbuy.com/site/3-year-acc_idental-protection-plan-geek-squad/9977006.p?_id=1218228677553&sku_id=9977006&cmp=RMX&ky=2d3GfEmNIzjA0vkzveHdZEBgpPCyMnLTJ',
//       category: 'BlackTie',
//       image:
//         'http://img.bbystatic.com/BestBuy_US/images/products/nonsku/default_hardlines_l.jpg',
//       numReviews: null,
//       shipping: 'Free shipping',
//       salePrice_range: '201 - 500',
//       object_id: '9977006',
//       categories: [null],
//     },
//   ],
// };
// export default data;

import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Zalmai',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Ahmad',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      // _id: '1',
      name: 'Nike Slim shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/images/p1.jpg', // 679px × 829px
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      // _id: '2',
      name: 'Adidas Fit Shirt',
      slug: 'adidas-fit-shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 250,
      countInStock: 0,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      // _id: '3',
      name: 'Nike Slim Pant',
      slug: 'nike-slim-pant',
      category: 'Pants',
      image: '/images/p3.jpg',
      price: 25,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      // _id: '4',
      name: 'Adidas Fit Pant',
      slug: 'adidas-fit-pant',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
  ],
};
export default data;
